#!/usr/bin/env bash
#
# autoDev — convention auto-detector. Scans the TARGET repo for the house patterns
# a fresh-context dev agent would otherwise reinvent (generated types, design
# system/theme, data layer, testing) and emits a prescriptive markdown report.
# /autodev:new and /autodev:loop run this and cache the result at .autodev/conventions.md,
# reading it explicitly at the top of each run (reference/manual.md references it) — so the
# dev persona inherits "use the generated types, use the theme" as BINDING context instead
# of hand-rolling types and hardcoding styles. The team's own AGENTS.md/CLAUDE.md still wins.
#
# Read-only on the repo. Usage: detect-conventions.sh <repo_path>
# Always prints SOMETHING (even "none detected → declare it"); never fails install.
set -uo pipefail

REPO="${1:-.}"
PKG="$REPO/package.json"

# dep present in dependencies or devDependencies?
have_dep() { [ -f "$PKG" ] && command -v jq >/dev/null 2>&1 && \
  jq -e --arg d "$1" '((.dependencies//{})+(.devDependencies//{}))|keys[]|select(test($d))' "$PKG" >/dev/null 2>&1; }
# a file matching glob-name exists somewhere sensible (not node_modules/dist)?
have_file() { find "$REPO" -maxdepth 3 \( -path '*/node_modules' -o -path '*/dist' -o -path '*/.git' \) -prune -o \
  -name "$1" -print 2>/dev/null | grep -q .; }

# Sample source files so we can MATCH the repo's actual conventions (lint enforces
# formatting; nothing enforces "how much to comment" — measuring it does).
# Exclude vendored/generated dirs plus autoDev's own runtime footprint (.claude/.autodev
# would otherwise pollute the client's measured density — this plugin runs from outside
# the client repo, so nothing else of ours ever lands inside it).
EXCL=( -path '*/node_modules' -o -path '*/dist' -o -path '*/build' -o -path '*/.git' -o -path '*/vendor' -o -path '*/.next' -o -path '*/out' -o -path '*/coverage' -o -path '*/__generated__' -o -path '*/.claude' -o -path '*/.autodev' )
list_src() { # <ext...> -> up to 500 source paths (newline-separated), excluding vendored/generated
  local args=() e; for e in "$@"; do args+=( -o -name "*.$e" ); done
  find "$REPO" \( "${EXCL[@]}" \) -prune -o -type f \( "${args[@]:1}" \) ! -name '*.generated.*' ! -name '*.min.*' -print 2>/dev/null | head -500
}
count_re() { # <regex> <newline-separated-files> -> match-line count across all (0 if no files)
  local re="$1" files="$2"
  [ -z "$files" ] && { echo 0; return; }
  printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 grep -hE "$re" 2>/dev/null | wc -l | tr -d ' '
}

echo "# Detected project conventions (auto-generated by /autodev:new / /autodev:loop)"
echo
echo "> Scanned \`$REPO\` when this ran. **These are BINDING** where your own files are"
echo "> silent — the dev agent adopts them, never reinvents them. Re-generated on every"
echo "> \`/autodev:new\` or \`/autodev:loop\` run. To refine or override, edit your **AGENTS.md /"
echo "> CLAUDE.md** (the team's own files are the top authority on conventions and win on conflict)."
echo

# ---- language / package manager / framework --------------------------------
echo "## Stack"
[ -f "$REPO/tsconfig.json" ] && echo "- **TypeScript** (\`tsconfig.json\`) — keep it type-safe; do not paper over types with \`any\`/\`as unknown\`."
if   [ -f "$REPO/bun.lockb" ];          then echo "- Package manager: **bun** — use \`bun\`."
elif [ -f "$REPO/pnpm-lock.yaml" ];     then echo "- Package manager: **pnpm** — use \`pnpm\`."
elif [ -f "$REPO/yarn.lock" ];          then echo "- Package manager: **yarn** — use \`yarn\`."
elif [ -f "$REPO/package-lock.json" ];  then echo "- Package manager: **npm** — use \`npm\`."; fi
have_dep '^react$'   && echo "- Framework: **React**."
have_dep '^vue$'     && echo "- Framework: **Vue**."
have_dep '^svelte$'  && echo "- Framework: **Svelte**."
have_dep '@angular/core' && echo "- Framework: **Angular**."
echo

# ---- TYPE GENERATION (the codegen gap) -------------------------------------
echo "## Types — source of truth (do NOT hand-roll these)"
TYPES_FOUND=0
if have_dep '@graphql-codegen' || have_file 'codegen.ts' || have_file 'codegen.yml' || have_file 'codegen.json' || have_file '*.generated.ts' || have_file '*.generated.tsx'; then
  echo "- **GraphQL code generation** detected (graphql-codegen / \`codegen.*\` / \`*.generated.ts\`)."
  echo "  → **Import the generated types** (\`*.generated.ts\` / \`__generated__/\`). **Never hand-write"
  echo "  GraphQL or schema-shaped types per component** — that's what forces \`as unknown\` casts and"
  echo "  duplicated types. Add an operation → run codegen, then import what it produces."
  TYPES_FOUND=1
fi
if have_file 'schema.prisma'; then
  echo "- **Prisma** (\`schema.prisma\`) → use the generated \`@prisma/client\` types; don't redeclare models."
  TYPES_FOUND=1
fi
if have_dep 'openapi-typescript' || have_dep '^orval$' || have_file 'openapi.*'; then
  echo "- **OpenAPI type generation** → import the generated API types; don't hand-type responses."
  TYPES_FOUND=1
fi
[ "$TYPES_FOUND" = 0 ] && echo "- ⚠️ No type-generation tool auto-detected. **Declare the type source-of-truth** in your AGENTS.md / CLAUDE.md (e.g. generated client types) so the agent doesn't invent per-component types."
echo

# ---- STYLING / DESIGN SYSTEM (the hardcoded-styles gap) --------------------
echo "## Styling — use the design system, do NOT hardcode"
STYLE_FOUND=0
if have_dep '@mui/material'; then
  echo "- **Material UI (MUI)** detected. → **Use the MUI theme** (\`useTheme\`/\`styled\`/\`sx\` with"
  echo "  theme tokens — \`theme.palette\`, \`theme.spacing\`). **Never hardcode** colors / spacing /"
  echo "  typography; if a token is missing, extend the theme, don't inline a literal."
  have_file 'theme.ts'  && echo "  (Theme file present — import and extend it.)"
  have_file 'theme.tsx' && echo "  (Theme file present — import and extend it.)"
  STYLE_FOUND=1
fi
if [ -f "$REPO/tailwind.config.js" ] || [ -f "$REPO/tailwind.config.ts" ] || have_file 'tailwind.config.*'; then
  echo "- **Tailwind** detected → use utility classes + the config's design tokens; no ad-hoc inline styles."
  STYLE_FOUND=1
fi
have_dep 'styled-components' && { echo "- **styled-components** → use the theme via \`ThemeProvider\`; no hardcoded literals."; STYLE_FOUND=1; }
have_dep '@emotion'          && { echo "- **Emotion** → theme tokens via the \`css\`/\`styled\` theme; no hardcoded literals."; STYLE_FOUND=1; }
have_dep '@chakra-ui'        && { echo "- **Chakra UI** → use theme tokens / style props; no hardcoded literals."; STYLE_FOUND=1; }
[ "$STYLE_FOUND" = 0 ] && echo "- ⚠️ No design system auto-detected. **Declare the styling convention** in your AGENTS.md / CLAUDE.md so the agent doesn't hardcode styles."
echo

# ---- data layer / testing --------------------------------------------------
echo "## Data layer & testing"
have_dep '@apollo/client'       && echo "- Data: **Apollo Client** — use its hooks/cache; follow existing query/fragment patterns."
have_dep '@tanstack/react-query' && echo "- Data: **TanStack Query** — use existing query keys/hooks."
have_dep '^urql$'               && echo "- Data: **urql** — follow existing client setup."
have_dep '^vitest$'   && echo "- Tests: **Vitest**."
have_dep '^jest$'     && echo "- Tests: **Jest**."
have_dep 'cypress'    && echo "- E2E: **Cypress**."
have_dep '@playwright/test' && echo "- E2E: **Playwright**."
echo

echo "## Comments — MATCH THIS REPO (measured), explain WHY not WHAT"
# Measure the repo's own comment-line density so the agent matches it instead of guessing.
SLASH=$(list_src ts tsx js jsx mjs cjs go rs java php swift kt c cc cpp h hpp cs scala dart)
HASH=$(list_src py rb sh bash ex exs pl r)
ALLSRC=$(printf '%s\n%s\n' "$SLASH" "$HASH" | grep -v '^$')
NFILES=$(printf '%s\n' "$ALLSRC" | grep -c . 2>/dev/null || echo 0)
NB=$(count_re '[^[:space:]]' "$ALLSRC")
CM=$(( $(count_re '^[[:space:]]*(//|/\*|\*)' "$SLASH") + $(count_re '^[[:space:]]*#' "$HASH") ))
if [ "${NB:-0}" -ge 150 ] && [ "$CM" -ge 0 ]; then
  PCT=$(( CM * 100 / NB ))
  if [ "$CM" -gt 0 ]; then RATIO=$(( NB / CM )); else RATIO=0; fi
  if   [ "$PCT" -lt 5 ];  then BUCKET="SPARSE — this codebase barely comments; add a comment only where intent is genuinely non-obvious."
  elif [ "$PCT" -lt 12 ]; then BUCKET="MODERATE — occasional why-comments; keep it light."
  else                         BUCKET="DOCUMENTED — comments are common here, but still WHY not WHAT (no narration)."; fi
  if [ "$CM" -gt 0 ]; then PER="≈1 comment line per $RATIO code lines"; else PER="essentially no comments"; fi
  echo "- **Measured density: ~${PCT}% of source lines are comments ($PER), across $NFILES sampled files → $BUCKET**"
  echo "- **Do not exceed this.** Write at or below the repo's own density — the dev agent's"
  echo "  default is to over-comment; this number is the ceiling, not a target to reach."
else
  echo "- (Too few source files to measure density reliably — match what you see in the files you touch.)"
fi
echo "- Explain **WHY**, not WHAT: comment only where intent isn't obvious. **Do NOT narrate**"
echo "  code that reads clearly, restate names in prose, or write header essays over trivial code."
echo "- **No commented-out code, no TODO without a tracked issue, no stale comments.**"
# Does the repo use doc-comments at all? Tell the agent whether to write them.
JSDOC=$(count_re '/\*\*' "$SLASH"); PYDOC=$(count_re '^[[:space:]]*("""|'\'''\'''\'')' "$HASH")
if [ "${JSDOC:-0}" -gt 5 ] || [ "${PYDOC:-0}" -gt 5 ]; then
  echo "- Doc-comments (JSDoc/docstrings) ARE used here — follow the existing style for public APIs; don't add them to trivial internals."
else
  echo "- This repo rarely uses doc-comments — don't introduce JSDoc/docstring blocks where the codebase doesn't already."
fi
# Formatting is tooling's job — point the agent at it instead of hand-styling.
FMT=""
[ -f "$REPO/.editorconfig" ] && FMT+="EditorConfig "
{ have_file '.prettierrc' || have_file '.prettierrc.*' || have_file 'prettier.config.*'; } && FMT+="Prettier "
{ have_file '.eslintrc' || have_file '.eslintrc.*' || have_file 'eslint.config.*'; } && FMT+="ESLint "
have_file '.rubocop.yml' && FMT+="RuboCop "
[ -n "$FMT" ] && echo "- **Formatting/style is enforced by: ${FMT}** — match it (run the formatter / your \`commands.lint\`); don't hand-style or fight the config."
echo

echo "## Always"
echo "- **Reuse before you write:** search for an existing component/hook/util that does the job"
echo "  before adding a new one. Duplicated logic / copy-pasted components are a defect, not a diff."
